################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productionDescription: Fiserv has been in the data aggregation business for more than 20 years. This means some of the largest and most innovative organizations use AllData® Aggregation to maximize the power of financial data aggregation. Access consumer-permissioned data covering dozens of vertical markets and account types including bank accounts, liability accounts including credit cards, investment and retirement accounts, as well as insurance and billers.
  whoIsItFor: Anyone looking to easily integrate financial data aggregation API's with new or existing applications, regardless of the underlying technology platform.
featuredFeatures:
  - title: Account Verification
    description: >
      AllData Aggregation makes setting up ACH payments easier for senders. 
      Users provide their credentials, and AllData Aggregation retrieves their accounts and routing numbers.
    tags: []
    bullets: []
    #links: ["docs/Online-Mobile-Digital/Wallets-AltPayments/Apple-Pay/Apple-Pay.md"]
    relatedDocs:
      - relatedDoc: 
        title: Common Use Cases
        description: >
          This document covers common use cases within the AllData Aggregation product, including a number of API solutions.
        link: "/docs/alldata-common-use-cases.md"
      - relatedDoc: 
        title: APIs and Add Account Widget 
        description: >
          This document addresses how to use AllData APIs and the Add Account widget for multiple use cases.
        link: "/docs/add-account.md"
      - relatedDoc: 
        title: Widget Integration Guide
        description: >
          This document covers ways to speed implementation by leveraging AllData widgets.
        link: "/docs/alldata-next-gen.md"
    relatedAPIs:
      - relatedAPI: 
        title: Sign On 
        description: >
          This API signs on to the AllData service, authenticates the user, and generates a session token. The session token is used in subsequent calls and to launch the Add Accounts widget, and it expires after 18 minutes of idle time.
        type: "post"        
        path: "/WealthManagementWeb/ws/UserMgmt/signon"
      - relatedAPI: 
        title: Get Account Details
        description: >
          This API fetches detail information about the account(s) associated with the account ID(s) passed to it. If no ID is passed, it returns information for all of the user's accounts.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getAccountDetails"
      - relatedAPI: 
        title: Get Bank Account Transactions
        description: This API fetches an account's transactions for a given date range.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getBankingTrans"
  - title: Money Movement
    description: >
      Through AllData Aggregation, accessing financial data needed for credit decisions happens quickly, eliminating the traditional paper chase. 
      AllData Aggregation also streamlines the process for the borrower.
    tags: []
    bullets: []
    #links: ["docs/Resources/API-Documents/Use-Our-APIs.md"]
    relatedDocs:
      - relatedDoc: 
        title: Common Use Cases
        description: >
          This document covers common use cases within the AllData Aggregation product, including a number of API solutions.
        link: "/docs/alldata-common-use-cases.md"
      - relatedDoc: 
        title: APIs and Add Account Widget 
        description: >
          This document addresses how to use AllData APIs and the Add Account widget for multiple use cases.
        link: "/docs/add-account.md"
      - relatedDoc: 
        title: Widget Integration Guide
        description: >
          This document covers ways to speed implementation by leveraging AllData widgets.
        link: "/docs/alldata-next-gen.md"
    relatedAPIs:
      - relatedAPI: 
        title: Sign On 
        description: >
          This API signs on to the AllData service, authenticates the user, and generates a session token. The session token is used in subsequent calls and to launch the Add Accounts widget, and it expires after 18 minutes of idle time.
        type: "post"        
        path: "/WealthManagementWeb/ws/UserMgmt/signon"
      - relatedAPI: 
        title: Get Account Details
        description: >
          This API fetches detail information about the account(s) associated with the account ID(s) passed to it. If no ID is passed, it returns information for all of the user's accounts.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getAccountDetails"
      - relatedAPI: 
        title: Get Bank Account Transactions
        description: This API fetches an account's transactions for a given date range.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getBankingTrans"
  - title: Lending and Account Opening
    description: AllData Aggregation lets businesses provide their consumers with a comprehensive view of their finances, enables advisors to provide deeper insight and better analysis, and empowers fintechs to develop innovative products and services.
    tags: []
    bullets: []
    relatedDocs:
      - relatedDoc: 
        title: Common Use Cases
        description: >
          This document covers common use cases within the AllData Aggregation product, including a number of API solutions.
        link: "/docs/alldata-common-use-cases.md"
      - relatedDoc: 
        title: APIs and Add Account Widget 
        description: >
          This document addresses how to use AllData APIs and the Add Account widget for multiple use cases.
        link: "/docs/add-account.md"
      - relatedDoc: 
        title: Widget Integration Guide
        description: >
          This document covers ways to speed implementation by leveraging AllData widgets.
        link: "/docs/alldata-next-gen.md"
    relatedAPIs:
      - relatedAPI: 
        title: Sign On 
        description: >
          This API signs on to the AllData service, authenticates the user, and generates a session token. The session token is used in subsequent calls and to launch the Add Accounts widget, and it expires after 18 minutes of idle time.
        type: "post"        
        path: "/WealthManagementWeb/ws/UserMgmt/signon"
      - relatedAPI: 
        title: Get Account Details
        description: >
          This API fetches detail information about the account(s) associated with the account ID(s) passed to it. If no ID is passed, it returns information for all of the user's accounts.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getAccountDetails"
      - relatedAPI: 
        title: Get Bank Account Transactions
        description: This API fetches an account's transactions for a given date range.
        type: "post"        
        path: "/WealthManagementWeb/ws/AccountDataInq/getBankingTrans"
